server:
  port: 8085
spring:
  application:
    name: user-preferences-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}
  data:
    mongodb:
      uri: ${MONGO_URI}

springdoc:
  api-docs:
    enabled: false

keycloak:
  url:
    token: ${KEYCLOAK_URL_TOKEN}
    authorization: ${KEYCLOAK_URL_AUTHORIZATION}
    
