server:
  port: 8081
spring:
  application:
    name: module-service
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI}

springdoc:
  api-docs:
    enabled: false

keycloak:
  url:
    token: ${KEYCLOAK_URL_TOKEN}
    authorization: ${KEYCLOAK_URL_AUTHORIZATION}