server:
  port: 8081
spring:
  application:
    name: module-service
  datasource:
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    url: ${DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  api-docs:
    enabled: false

