server:
  port: 8088
spring:
  application:
    name: card-service
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5306/cardsdb
  jpa:
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/learnify-dev

springdoc:
  api-docs:
    enabled: false

